### ISSUE TITLE
Hi, any way I could help?

### ISSUE THREAD

**Issue by Xoronic** [aquawicket/DigitalKnob#115]
Hi, I saw this repo and I *think* I like the idea behind it, but it's pretty vague...

Is there any way I could help writing documentation, examples, a more attractive readme? (It's really hard to see what DigitalKnob actually does from the readme). I've got c++, javascript, typescript and CMake experience. Please let me know :)

**Comment by aquawicket** [comment]
Yes, the documentation is really lacking. I spend most of my time coding so I haven't really gotten around to it. Some of the stuff in DKDocs is pretty outdated but still relevant. I can give you a crash course on DigitalKnob after the weekend.

**Comment by Xoronic** [comment]
Sure, where can I reach you? Discord, Gitter, Slack, Skype, something like that?

**Comment by aquawicket** [comment]
After review, Digitalknob is still too young and pre-beta to do Docs yet.
Docs would have to be updated as often as the code, to keep up. 
I will re-open this issue when the time arrives. 

closing for now.

**Comment by aquawicket** [comment]
If you are still interested in this project, I'd like to Create a basic outline of how it works. Might need a hand. Thanks.
